version: '3'

services:

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80

  matomo-nginx:
    build: 
      context: ./matomo/nginx
    volumes:
      - ./matomo/matomo:/var/www
      - ./ssl/matomo.gyhost.icu:/ssl
    depends_on:
        - matomo-php-fpm

  matomo-php-fpm:
    build:
      context: ./matomo/php-fpm
    volumes:
      - ./matomo/matomo:/var/www
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql