version: '3'

services:

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./ssl/matomo.gyhost.icu:/ssl
    ports:
      - 80:80
      - 443:443

  matomo_nginx:
    build: 
      context: ./matomo/nginx
    volumes:
      - ./matomo/matomo:/var/www
    depends_on:
      - matomo-php-fpm

  matomo_php_fpm:
    build:
      context: ./matomo/php-fpm
    volumes:
      - ./matomo/matomo:/var/www

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql