version: '3'

services:

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./ssl:/ssl
    depends_on:
      - matomo-nginx
      - travel-path-explorer
      - mastodon-web
      - ibike-map
    ports:
      - 80:80
      - 443:443

  matomo-nginx:
    build: 
      context: ./matomo/nginx
    volumes:
      - ./matomo/matomo:/var/www
    depends_on:
      - matomo-php-fpm

  matomo-php-fpm:
    build:
      context: ./matomo/php-fpm
    volumes:
      - ./matomo/matomo:/var/www

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql

  travel-path-explorer:
      image: gychen/travel_path_explorer
      env_file: .env
      volumes:
        - ./travel_path_explorer_data:/data
  
  mastodon-db:
    image: postgres:9.6-alpine
    volumes:
      - ./mastodon/postgres:/var/lib/postgresql/data

  mastodon-redis:
    image: redis:4.0-alpine
    volumes:
      - ./mastodon/redis:/data

  mastodon-web:
    image: tootsuite/mastodon:v2.6.5
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: .mastodon.env
    depends_on:
      - mastodon-db
      - mastodon-redis
    volumes:
      - ./mastodon/public/system:/mastodon/public/system

  mastodon-streaming:
    image: tootsuite/mastodon:v2.6.5
    command: yarn start
    env_file: .mastodon.env
    depends_on:
      - mastodon-db
      - mastodon-redis

  mastodon-sidekiq:
    image: tootsuite/mastodon:v2.6.5
    command: bundle exec sidekiq
    env_file: .mastodon.env
    depends_on:
      - mastodon-db
      - mastodon-redis
    volumes:
      - ./mastodon/public/system:/mastodon/public/system

  ibike-map:
    image: gychen/ibike_map
    env_file: .ibike-map.env
    depends_on:
      - ibike-map-db

  ibike-map-db:
    image: mongo
    volumes:
      - ibike-map-db-data:/data/db

volumes:
  ibike-map-db-data: