version: '3'
services:
  mal-collector:
    image: "octo-barnacle"
    env_file: .env
    depends_on:
      - redis
      - mongo
  redis:
    image: "redis"
    command: redis-server --appendonly yes
    volumes:
      - "redisdata:/data"
  mongo:
    image: "mongo"
    volumes:
      - "mongodata:/data/db"
volumes:
  redisdata:
  mongodata:
