version: "3"
services:
  gitea:
    image: gitea/gitea:latest
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - "./data:/data"
  db:
    image: postgres
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_PASSWORD: example
