version: "3"
services:
  mysql:
    image: mysql
    deploy:
      replicas: 1
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - "./data:/var/lib/mysql"
    ports:
      - "3306:3306"
