FROM alpine

RUN apk update
RUN apk add python3 python3-dev
ADD get-pip.py /root/get-pip.py
RUN python3 /root/get-pip.py
RUN apk add build-base
RUN pip3 install jupyter

ENTRYPOINT ["jupyter", "notebook", "--ip", "0.0.0.0", "--allow-root", "--notebook-dir", "/data"]
VOLUME ["/data"]
EXPOSE 8888
