version: "3"
services:
  php:
    image: gychen/rpi-php
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
    volumes:
      - "./data:/var/www/html"
  mysql:
    image: hypriot/rpi-mysql
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - "./mysql-data:/var/lib/mysql"
