version: '3'

services:

  nginx:
    build:
      context: ./nginx
    volumes:
      - ./ssl:/ssl
    ports:
      - 80:80
      - 443:443
    depends_on:
        - web

  db:
    image: postgres:9.6-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data

  redis:
    image: redis:4.0-alpine
    volumes:
      - ./redis:/data

  web:
    image: tootsuite/mastodon:v2.6.2
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - ./public/system:/mastodon/public/system